version: '3.8'

services:
  reminder_bot:
    build: .
    container_name: telegram_reminder_bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data # Persist the SQLite database and other data
    restart: always
